[2016-07-31 12:23:13 +0000] [18122] [DEBUG] Current configuration:
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f186af72ed8>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f186af72c08>
  pre_fork: <function pre_fork at 0x7f186af72d70>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 1
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f186af72aa0>
  pre_exec: <function pre_exec at 0x7f186af7b500>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f186af7b0c8>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f186af7bb90>
  config: None
  logconfig: None
  check_config: False
  statsd_prefix: 
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f186af7b668>
  post_request: <function post_request at 0x7f186af7b758>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f186af7b230>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f186af7b8c0>
  chdir: /home/ubuntu/djangoApp
  paste: None
  default_proc_name: djangoApp/core/djangoApp.wsgi:application
  errorlog: /home/ubuntu/djangoApp/gunicorn.log
  loglevel: debug
  capture_output: False
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f186af72938>
  worker_abort: <function worker_abort at 0x7f186af7b398>
  bind: ['127.0.0.1:8000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f186af7ba28>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2016-07-31 12:23:13 +0000] [18122] [INFO] Starting gunicorn 19.6.0
[2016-07-31 12:23:13 +0000] [18122] [DEBUG] Arbiter booted
[2016-07-31 12:23:13 +0000] [18122] [INFO] Listening at: http://127.0.0.1:8000 (18122)
[2016-07-31 12:23:13 +0000] [18122] [INFO] Using worker: sync
[2016-07-31 12:23:13 +0000] [18127] [INFO] Booting worker with pid: 18127
[2016-07-31 12:23:13 +0000] [18127] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/djangoApp/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.virtualenvs/djangoApp/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.virtualenvs/djangoApp/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.virtualenvs/djangoApp/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.virtualenvs/djangoApp/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.virtualenvs/djangoApp/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.virtualenvs/djangoApp/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: Import by filename is not supported.
[2016-07-31 12:23:13 +0000] [18127] [INFO] Worker exiting (pid: 18127)
[2016-07-31 12:23:13 +0000] [18122] [INFO] Shutting down: Master
[2016-07-31 12:23:13 +0000] [18122] [INFO] Reason: Worker failed to boot.
[2016-07-31 12:42:13 +0000] [18285] [DEBUG] Current configuration:
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f4f54067ed8>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f4f54067c08>
  pre_fork: <function pre_fork at 0x7f4f54067d70>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f4f54067aa0>
  pre_exec: <function pre_exec at 0x7f4f54070500>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f4f540700c8>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f4f54070b90>
  config: None
  logconfig: None
  check_config: False
  statsd_prefix: 
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f4f54070668>
  post_request: <function post_request at 0x7f4f54070758>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f4f54070230>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f4f540708c0>
  chdir: /home/ubuntu/djangoApp
  paste: None
  default_proc_name: core.wsgi:application
  errorlog: /home/ubuntu/djangoApp/gunicorn.log
  loglevel: debug
  capture_output: False
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f4f54067938>
  worker_abort: <function worker_abort at 0x7f4f54070398>
  bind: ['0.0.0.0:5000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f4f54070a28>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2016-07-31 12:42:13 +0000] [18285] [INFO] Starting gunicorn 19.6.0
[2016-07-31 12:42:13 +0000] [18285] [DEBUG] Arbiter booted
[2016-07-31 12:42:13 +0000] [18285] [INFO] Listening at: http://0.0.0.0:5000 (18285)
[2016-07-31 12:42:13 +0000] [18285] [INFO] Using worker: sync
[2016-07-31 12:42:13 +0000] [18290] [INFO] Booting worker with pid: 18290
[2016-07-31 12:42:13 +0000] [18291] [INFO] Booting worker with pid: 18291
[2016-07-31 12:42:14 +0000] [18294] [INFO] Booting worker with pid: 18294
[2016-07-31 12:42:14 +0000] [18285] [DEBUG] 3 workers
[2016-07-31 12:42:37 +0000] [18354] [DEBUG] Current configuration:
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f9baa6b2ed8>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f9baa6b2c08>
  pre_fork: <function pre_fork at 0x7f9baa6b2d70>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f9baa6b2aa0>
  pre_exec: <function pre_exec at 0x7f9baa6bb500>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f9baa6bb0c8>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f9baa6bbb90>
  config: None
  logconfig: None
  check_config: False
  statsd_prefix: 
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f9baa6bb668>
  post_request: <function post_request at 0x7f9baa6bb758>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f9baa6bb230>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f9baa6bb8c0>
  chdir: /home/ubuntu/djangoApp
  paste: None
  default_proc_name: core.wsgi:application
  errorlog: /home/ubuntu/djangoApp/gunicorn.log
  loglevel: debug
  capture_output: False
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f9baa6b2938>
  worker_abort: <function worker_abort at 0x7f9baa6bb398>
  bind: ['0.0.0.0:5000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f9baa6bba28>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2016-07-31 12:42:37 +0000] [18354] [INFO] Starting gunicorn 19.6.0
[2016-07-31 12:42:37 +0000] [18354] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2016-07-31 12:42:37 +0000] [18354] [DEBUG] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2016-07-31 12:42:37 +0000] [18354] [ERROR] Retrying in 1 second.
[2016-07-31 12:42:38 +0000] [18354] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2016-07-31 12:42:38 +0000] [18354] [DEBUG] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2016-07-31 12:42:38 +0000] [18354] [ERROR] Retrying in 1 second.
[2016-07-31 12:42:39 +0000] [18354] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2016-07-31 12:42:39 +0000] [18354] [DEBUG] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2016-07-31 12:42:39 +0000] [18354] [ERROR] Retrying in 1 second.
[2016-07-31 12:42:40 +0000] [18354] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2016-07-31 12:42:40 +0000] [18354] [DEBUG] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2016-07-31 12:42:40 +0000] [18354] [ERROR] Retrying in 1 second.
[2016-07-31 12:42:41 +0000] [18354] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2016-07-31 12:42:41 +0000] [18354] [DEBUG] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2016-07-31 12:42:41 +0000] [18354] [ERROR] Retrying in 1 second.
[2016-07-31 12:42:42 +0000] [18354] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2016-07-31 12:43:53 +0000] [18404] [DEBUG] Current configuration:
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f2387b39ed8>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f2387b39c08>
  pre_fork: <function pre_fork at 0x7f2387b39d70>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f2387b39aa0>
  pre_exec: <function pre_exec at 0x7f2387b42500>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f2387b420c8>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f2387b42b90>
  config: None
  logconfig: None
  check_config: False
  statsd_prefix: 
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f2387b42668>
  post_request: <function post_request at 0x7f2387b42758>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f2387b42230>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f2387b428c0>
  chdir: /home/ubuntu/djangoApp
  paste: None
  default_proc_name: core.wsgi:application
  errorlog: /home/ubuntu/djangoApp/gunicorn.log
  loglevel: debug
  capture_output: False
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f2387b39938>
  worker_abort: <function worker_abort at 0x7f2387b42398>
  bind: ['127.0.0.1:8000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f2387b42a28>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2016-07-31 12:43:53 +0000] [18404] [INFO] Starting gunicorn 19.6.0
[2016-07-31 12:43:53 +0000] [18404] [DEBUG] Arbiter booted
[2016-07-31 12:43:53 +0000] [18404] [INFO] Listening at: http://127.0.0.1:8000 (18404)
[2016-07-31 12:43:53 +0000] [18404] [INFO] Using worker: sync
[2016-07-31 12:43:53 +0000] [18409] [INFO] Booting worker with pid: 18409
[2016-07-31 12:43:53 +0000] [18412] [INFO] Booting worker with pid: 18412
[2016-07-31 12:43:53 +0000] [18415] [INFO] Booting worker with pid: 18415
[2016-07-31 12:43:53 +0000] [18404] [DEBUG] 3 workers
[2016-07-31 12:55:30 +0000] [18590] [DEBUG] Current configuration:
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f49a3232ed8>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f49a3232c08>
  pre_fork: <function pre_fork at 0x7f49a3232d70>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f49a3232aa0>
  pre_exec: <function pre_exec at 0x7f49a323b500>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f49a323b0c8>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f49a323bb90>
  config: None
  logconfig: None
  check_config: False
  statsd_prefix: 
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f49a323b668>
  post_request: <function post_request at 0x7f49a323b758>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f49a323b230>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f49a323b8c0>
  chdir: /home/ubuntu/djangoApp
  paste: None
  default_proc_name: core.wsgi:application
  errorlog: /home/ubuntu/djangoApp/gunicorn.log
  loglevel: debug
  capture_output: False
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f49a3232938>
  worker_abort: <function worker_abort at 0x7f49a323b398>
  bind: ['127.0.0.1:8000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f49a323ba28>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2016-07-31 12:55:30 +0000] [18590] [INFO] Starting gunicorn 19.6.0
[2016-07-31 12:55:30 +0000] [18590] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2016-07-31 12:55:30 +0000] [18590] [DEBUG] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2016-07-31 12:55:30 +0000] [18590] [ERROR] Retrying in 1 second.
[2016-07-31 12:55:31 +0000] [18590] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2016-07-31 12:55:31 +0000] [18590] [DEBUG] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2016-07-31 12:55:31 +0000] [18590] [ERROR] Retrying in 1 second.
[2016-07-31 12:55:32 +0000] [18590] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2016-07-31 12:55:32 +0000] [18590] [DEBUG] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2016-07-31 12:55:32 +0000] [18590] [ERROR] Retrying in 1 second.
[2016-07-31 12:55:33 +0000] [18590] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2016-07-31 12:55:33 +0000] [18590] [DEBUG] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2016-07-31 12:55:33 +0000] [18590] [ERROR] Retrying in 1 second.
[2016-07-31 12:55:34 +0000] [18590] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2016-07-31 12:55:34 +0000] [18590] [DEBUG] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2016-07-31 12:55:34 +0000] [18590] [ERROR] Retrying in 1 second.
[2016-07-31 12:55:35 +0000] [18590] [ERROR] Can't connect to ('127.0.0.1', 8000)
[2016-07-31 12:56:12 +0000] [18657] [DEBUG] Current configuration:
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7fb057410ed8>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7fb057410c08>
  pre_fork: <function pre_fork at 0x7fb057410d70>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7fb057410aa0>
  pre_exec: <function pre_exec at 0x7fb057419500>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7fb0574190c8>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7fb057419b90>
  config: None
  logconfig: None
  check_config: False
  statsd_prefix: 
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7fb057419668>
  post_request: <function post_request at 0x7fb057419758>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7fb057419230>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7fb0574198c0>
  chdir: /home/ubuntu/djangoApp
  paste: None
  default_proc_name: core.wsgi:application
  errorlog: /home/ubuntu/djangoApp/gunicorn.log
  loglevel: debug
  capture_output: False
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7fb057410938>
  worker_abort: <function worker_abort at 0x7fb057419398>
  bind: ['127.0.0.1:8000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7fb057419a28>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2016-07-31 12:56:12 +0000] [18657] [INFO] Starting gunicorn 19.6.0
[2016-07-31 12:56:12 +0000] [18657] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2016-07-31 12:56:12 +0000] [18657] [DEBUG] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2016-07-31 12:56:12 +0000] [18657] [ERROR] Retrying in 1 second.
[2016-07-31 12:56:13 +0000] [18657] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2016-07-31 12:56:13 +0000] [18657] [DEBUG] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2016-07-31 12:56:13 +0000] [18657] [ERROR] Retrying in 1 second.
[2016-07-31 12:56:14 +0000] [18657] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2016-07-31 12:56:14 +0000] [18657] [DEBUG] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2016-07-31 12:56:14 +0000] [18657] [ERROR] Retrying in 1 second.
[2016-07-31 12:56:15 +0000] [18657] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2016-07-31 12:56:15 +0000] [18657] [DEBUG] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2016-07-31 12:56:15 +0000] [18657] [ERROR] Retrying in 1 second.
[2016-07-31 12:56:16 +0000] [18657] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2016-07-31 12:56:16 +0000] [18657] [DEBUG] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2016-07-31 12:56:16 +0000] [18657] [ERROR] Retrying in 1 second.
[2016-07-31 12:56:17 +0000] [18657] [ERROR] Can't connect to ('127.0.0.1', 8000)
[2016-07-31 12:58:40 +0000] [18290] [INFO] Worker exiting (pid: 18290)
[2016-07-31 12:58:40 +0000] [18291] [INFO] Worker exiting (pid: 18291)
[2016-07-31 12:58:40 +0000] [18294] [INFO] Worker exiting (pid: 18294)
[2016-07-31 12:58:40 +0000] [18415] [INFO] Worker exiting (pid: 18415)
[2016-07-31 12:58:40 +0000] [18412] [INFO] Worker exiting (pid: 18412)
[2016-07-31 12:58:40 +0000] [18409] [INFO] Worker exiting (pid: 18409)
[2016-07-31 12:58:40 +0000] [18404] [INFO] Handling signal: term
[2016-07-31 12:58:40 +0000] [18285] [INFO] Handling signal: term
[2016-07-31 12:58:40 +0000] [18404] [INFO] Shutting down: Master
[2016-07-31 12:58:40 +0000] [18285] [INFO] Shutting down: Master
[2016-07-31 12:59:04 +0000] [18718] [DEBUG] Current configuration:
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7fcc4632fed8>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7fcc4632fc08>
  pre_fork: <function pre_fork at 0x7fcc4632fd70>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7fcc4632faa0>
  pre_exec: <function pre_exec at 0x7fcc46338500>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7fcc463380c8>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7fcc46338b90>
  config: None
  logconfig: None
  check_config: False
  statsd_prefix: 
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7fcc46338668>
  post_request: <function post_request at 0x7fcc46338758>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7fcc46338230>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7fcc463388c0>
  chdir: /home/ubuntu/djangoApp
  paste: None
  default_proc_name: core.wsgi:application
  errorlog: /home/ubuntu/djangoApp/gunicorn.log
  loglevel: debug
  capture_output: False
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7fcc4632f938>
  worker_abort: <function worker_abort at 0x7fcc46338398>
  bind: ['127.0.0.1:8000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7fcc46338a28>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2016-07-31 12:59:04 +0000] [18718] [INFO] Starting gunicorn 19.6.0
[2016-07-31 12:59:04 +0000] [18718] [DEBUG] Arbiter booted
[2016-07-31 12:59:04 +0000] [18718] [INFO] Listening at: http://127.0.0.1:8000 (18718)
[2016-07-31 12:59:04 +0000] [18718] [INFO] Using worker: sync
[2016-07-31 12:59:04 +0000] [18723] [INFO] Booting worker with pid: 18723
[2016-07-31 12:59:04 +0000] [18726] [INFO] Booting worker with pid: 18726
[2016-07-31 12:59:04 +0000] [18727] [INFO] Booting worker with pid: 18727
[2016-07-31 12:59:04 +0000] [18718] [DEBUG] 3 workers
[2016-07-31 12:59:21 +0000] [18718] [INFO] Handling signal: term
[2016-07-31 12:59:21 +0000] [18723] [INFO] Worker exiting (pid: 18723)
[2016-07-31 12:59:21 +0000] [18726] [INFO] Worker exiting (pid: 18726)
[2016-07-31 12:59:21 +0000] [18727] [INFO] Worker exiting (pid: 18727)
[2016-07-31 12:59:21 +0000] [18718] [INFO] Shutting down: Master
[2016-07-31 12:59:43 +0000] [18791] [DEBUG] Current configuration:
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f0bce6a6ed8>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f0bce6a6c08>
  pre_fork: <function pre_fork at 0x7f0bce6a6d70>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f0bce6a6aa0>
  pre_exec: <function pre_exec at 0x7f0bce6af500>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f0bce6af0c8>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f0bce6afb90>
  config: None
  logconfig: None
  check_config: False
  statsd_prefix: 
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f0bce6af668>
  post_request: <function post_request at 0x7f0bce6af758>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f0bce6af230>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f0bce6af8c0>
  chdir: /home/ubuntu/djangoApp
  paste: None
  default_proc_name: core.wsgi:application
  errorlog: /home/ubuntu/djangoApp/gunicorn.log
  loglevel: debug
  capture_output: False
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f0bce6a6938>
  worker_abort: <function worker_abort at 0x7f0bce6af398>
  bind: ['127.0.0.1:8000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f0bce6afa28>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2016-07-31 12:59:43 +0000] [18791] [INFO] Starting gunicorn 19.6.0
[2016-07-31 12:59:43 +0000] [18791] [DEBUG] Arbiter booted
[2016-07-31 12:59:43 +0000] [18791] [INFO] Listening at: http://127.0.0.1:8000 (18791)
[2016-07-31 12:59:43 +0000] [18791] [INFO] Using worker: sync
[2016-07-31 12:59:43 +0000] [18796] [INFO] Booting worker with pid: 18796
[2016-07-31 12:59:43 +0000] [18797] [INFO] Booting worker with pid: 18797
[2016-07-31 12:59:43 +0000] [18800] [INFO] Booting worker with pid: 18800
[2016-07-31 12:59:43 +0000] [18791] [DEBUG] 3 workers
[2016-07-31 13:01:19 +0000] [18791] [INFO] Handling signal: term
[2016-07-31 13:01:19 +0000] [18800] [INFO] Worker exiting (pid: 18800)
[2016-07-31 13:01:19 +0000] [18796] [INFO] Worker exiting (pid: 18796)
[2016-07-31 13:01:19 +0000] [18797] [INFO] Worker exiting (pid: 18797)
[2016-07-31 13:01:19 +0000] [18791] [INFO] Shutting down: Master
[2016-07-31 13:03:10 +0000] [18890] [DEBUG] Current configuration:
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f8fb8d11ed8>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f8fb8d11c08>
  pre_fork: <function pre_fork at 0x7f8fb8d11d70>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f8fb8d11aa0>
  pre_exec: <function pre_exec at 0x7f8fb8d1a500>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f8fb8d1a0c8>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f8fb8d1ab90>
  config: None
  logconfig: None
  check_config: False
  statsd_prefix: 
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f8fb8d1a668>
  post_request: <function post_request at 0x7f8fb8d1a758>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f8fb8d1a230>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f8fb8d1a8c0>
  chdir: /home/ubuntu/djangoApp
  paste: None
  default_proc_name: core.wsgi:application
  errorlog: /home/ubuntu/djangoApp/gunicorn.log
  loglevel: debug
  capture_output: False
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f8fb8d11938>
  worker_abort: <function worker_abort at 0x7f8fb8d1a398>
  bind: ['127.0.0.1:8000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f8fb8d1aa28>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2016-07-31 13:03:10 +0000] [18890] [INFO] Starting gunicorn 19.6.0
[2016-07-31 13:03:10 +0000] [18890] [DEBUG] Arbiter booted
[2016-07-31 13:03:10 +0000] [18890] [INFO] Listening at: http://127.0.0.1:8000 (18890)
[2016-07-31 13:03:10 +0000] [18890] [INFO] Using worker: sync
[2016-07-31 13:03:10 +0000] [18895] [INFO] Booting worker with pid: 18895
[2016-07-31 13:03:10 +0000] [18896] [INFO] Booting worker with pid: 18896
[2016-07-31 13:03:10 +0000] [18901] [INFO] Booting worker with pid: 18901
[2016-07-31 13:03:10 +0000] [18890] [DEBUG] 3 workers
[2016-07-31 13:14:12 +0000] [18895] [DEBUG] GET /
Not Found: /
[2016-07-31 13:14:18 +0000] [18901] [DEBUG] GET /sample
[2016-07-31 13:14:18 +0000] [18895] [DEBUG] GET /sample/
[2016-07-31 13:14:18 +0000] [18896] [DEBUG] GET /sample/
[2016-07-31 13:16:05 +0000] [18896] [DEBUG] GET /sample/
[2016-07-31 13:16:38 +0000] [18896] [DEBUG] GET /
Not Found: /
[2016-07-31 13:16:44 +0000] [18895] [DEBUG] GET /sample/
[2016-07-31 13:19:05 +0000] [18895] [DEBUG] GET /sample
[2016-07-31 13:19:05 +0000] [18901] [DEBUG] GET /sample/
[2016-07-31 13:19:08 +0000] [18896] [DEBUG] GET /sample
[2016-07-31 13:19:08 +0000] [18895] [DEBUG] GET /sample/
[2016-07-31 13:34:02 +0000] [18895] [DEBUG] GET /
Not Found: /
[2016-07-31 13:34:16 +0000] [18896] [DEBUG] GET /admin
[2016-07-31 13:34:16 +0000] [18901] [DEBUG] GET /admin/
[2016-07-31 13:34:16 +0000] [18896] [DEBUG] GET /admin/login/
[2016-07-31 13:34:16 +0000] [18901] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:34:16 +0000] [18895] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:34:48 +0000] [18896] [DEBUG] POST /admin/login/
[2016-07-31 13:34:49 +0000] [18895] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:34:49 +0000] [18901] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:36:30 +0000] [18901] [DEBUG] POST /admin/login/
[2016-07-31 13:36:30 +0000] [18895] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:36:30 +0000] [18896] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:36:35 +0000] [18901] [DEBUG] POST /admin/login/
[2016-07-31 13:36:36 +0000] [18896] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:36:36 +0000] [18895] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:36:44 +0000] [18901] [DEBUG] POST /admin/login/
[2016-07-31 13:36:44 +0000] [18895] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:36:44 +0000] [18896] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:41:43 +0000] [18896] [DEBUG] POST /admin/login/
[2016-07-31 13:41:43 +0000] [18895] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:41:43 +0000] [18901] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:46:02 +0000] [18901] [DEBUG] POST /admin/login/
[2016-07-31 13:46:02 +0000] [18895] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:46:02 +0000] [18896] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:46:06 +0000] [18901] [DEBUG] POST /admin/login/
[2016-07-31 13:46:07 +0000] [18896] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:46:07 +0000] [18895] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:46:10 +0000] [18901] [DEBUG] POST /admin/login/
[2016-07-31 13:46:10 +0000] [18895] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:46:10 +0000] [18896] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:46:18 +0000] [18901] [DEBUG] POST /admin/login/
[2016-07-31 13:46:18 +0000] [18896] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:46:18 +0000] [18895] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:46:26 +0000] [18901] [DEBUG] POST /admin/login/
[2016-07-31 13:46:26 +0000] [18895] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:46:27 +0000] [18896] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:46:45 +0000] [18901] [DEBUG] POST /admin/login/
[2016-07-31 13:46:45 +0000] [18896] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:46:45 +0000] [18895] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:46:58 +0000] [18901] [DEBUG] POST /admin/login/
[2016-07-31 13:46:58 +0000] [18895] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:46:58 +0000] [18896] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:47:17 +0000] [18901] [DEBUG] POST /admin/login/
[2016-07-31 13:47:17 +0000] [18896] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:47:17 +0000] [18895] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:48:35 +0000] [18895] [DEBUG] POST /admin/login/
[2016-07-31 13:48:35 +0000] [18896] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:48:35 +0000] [18901] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:48:41 +0000] [18895] [DEBUG] POST /admin/login/
[2016-07-31 13:48:41 +0000] [18901] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:48:41 +0000] [18896] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:48:43 +0000] [18895] [DEBUG] GET /admin/
[2016-07-31 13:48:43 +0000] [18901] [DEBUG] GET /admin/login/
[2016-07-31 13:48:44 +0000] [18895] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:48:44 +0000] [18896] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:48:51 +0000] [18901] [DEBUG] POST /admin/login/
[2016-07-31 13:48:51 +0000] [18895] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:48:51 +0000] [18896] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:56:05 +0000] [18896] [DEBUG] GET /admin/login/
[2016-07-31 13:56:05 +0000] [18901] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:56:05 +0000] [18895] [DEBUG] GET /static/admin/css/login.css
Not Found: /static/admin/css/login.css
[2016-07-31 13:56:12 +0000] [18896] [DEBUG] POST /admin/login/
[2016-07-31 13:56:12 +0000] [18901] [DEBUG] GET /admin/
[2016-07-31 13:56:12 +0000] [18896] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 13:56:12 +0000] [18895] [DEBUG] GET /static/admin/css/dashboard.css
Not Found: /static/admin/css/dashboard.css
[2016-07-31 14:04:07 +0000] [18896] [DEBUG] GET /admin/
[2016-07-31 14:04:07 +0000] [18895] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 14:04:07 +0000] [18901] [DEBUG] GET /static/admin/css/dashboard.css
Not Found: /static/admin/css/dashboard.css
[2016-07-31 14:04:12 +0000] [18896] [DEBUG] GET /admin/
[2016-07-31 14:04:13 +0000] [18895] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 14:04:13 +0000] [18901] [DEBUG] GET /static/admin/css/dashboard.css
Not Found: /static/admin/css/dashboard.css
[2016-07-31 14:04:34 +0000] [18890] [INFO] Handling signal: term
[2016-07-31 14:04:34 +0000] [18896] [INFO] Worker exiting (pid: 18896)
[2016-07-31 14:04:34 +0000] [18895] [INFO] Worker exiting (pid: 18895)
[2016-07-31 14:04:34 +0000] [18901] [INFO] Worker exiting (pid: 18901)
[2016-07-31 14:04:34 +0000] [18890] [INFO] Shutting down: Master
[2016-07-31 14:05:24 +0000] [19471] [DEBUG] Current configuration:
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7ff76ff0fed8>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7ff76ff0fc08>
  pre_fork: <function pre_fork at 0x7ff76ff0fd70>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7ff76ff0faa0>
  pre_exec: <function pre_exec at 0x7ff76ff18500>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7ff76ff180c8>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7ff76ff18b90>
  config: None
  logconfig: None
  check_config: False
  statsd_prefix: 
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7ff76ff18668>
  post_request: <function post_request at 0x7ff76ff18758>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7ff76ff18230>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7ff76ff188c0>
  chdir: /home/ubuntu/djangoApp
  paste: None
  default_proc_name: core.wsgi:application
  errorlog: /home/ubuntu/djangoApp/gunicorn.log
  loglevel: debug
  capture_output: False
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7ff76ff0f938>
  worker_abort: <function worker_abort at 0x7ff76ff18398>
  bind: ['127.0.0.1:8000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7ff76ff18a28>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2016-07-31 14:05:24 +0000] [19471] [INFO] Starting gunicorn 19.6.0
[2016-07-31 14:05:24 +0000] [19471] [DEBUG] Arbiter booted
[2016-07-31 14:05:24 +0000] [19471] [INFO] Listening at: http://127.0.0.1:8000 (19471)
[2016-07-31 14:05:24 +0000] [19471] [INFO] Using worker: sync
[2016-07-31 14:05:24 +0000] [19476] [INFO] Booting worker with pid: 19476
[2016-07-31 14:05:24 +0000] [19479] [INFO] Booting worker with pid: 19479
[2016-07-31 14:05:24 +0000] [19480] [INFO] Booting worker with pid: 19480
[2016-07-31 14:05:24 +0000] [19471] [DEBUG] 3 workers
[2016-07-31 14:05:29 +0000] [19476] [DEBUG] GET /admin/
[2016-07-31 14:05:29 +0000] [19480] [DEBUG] GET /static/admin/css/base.css
[2016-07-31 14:05:29 +0000] [19479] [DEBUG] GET /static/admin/css/dashboard.css
Not Found: /static/admin/css/base.css
Not Found: /static/admin/css/dashboard.css
[2016-07-31 14:05:33 +0000] [19476] [DEBUG] GET /
Not Found: /
[2016-07-31 14:05:37 +0000] [19480] [DEBUG] GET /admin
[2016-07-31 14:05:38 +0000] [19479] [DEBUG] GET /admin/
[2016-07-31 14:05:38 +0000] [19480] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 14:05:38 +0000] [19476] [DEBUG] GET /static/admin/css/dashboard.css
Not Found: /static/admin/css/dashboard.css
[2016-07-31 14:05:42 +0000] [19479] [DEBUG] GET /admin/
[2016-07-31 14:05:42 +0000] [19480] [DEBUG] GET /static/admin/css/dashboard.css
Not Found: /static/admin/css/dashboard.css
[2016-07-31 14:05:42 +0000] [19476] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 14:05:50 +0000] [19479] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 14:05:50 +0000] [19480] [DEBUG] GET /static/admin/css/dashboard.css
Not Found: /static/admin/css/dashboard.css
[2016-07-31 14:09:30 +0000] [19480] [DEBUG] GET /admin/
[2016-07-31 14:09:30 +0000] [19476] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 14:09:30 +0000] [19479] [DEBUG] GET /static/admin/css/dashboard.css
Not Found: /static/admin/css/dashboard.css
[2016-07-31 14:09:52 +0000] [19480] [DEBUG] GET /static
Not Found: /static
[2016-07-31 14:09:56 +0000] [19476] [DEBUG] GET /admin/
[2016-07-31 14:10:20 +0000] [19476] [DEBUG] GET /admin/
[2016-07-31 14:10:20 +0000] [19480] [DEBUG] GET /static/admin/css/dashboard.css
Not Found: /static/admin/css/dashboard.css
[2016-07-31 14:10:20 +0000] [19479] [DEBUG] GET /static/admin/css/base.css
Not Found: /static/admin/css/base.css
[2016-07-31 14:15:40 +0000] [19471] [INFO] Handling signal: term
[2016-07-31 14:15:40 +0000] [19476] [INFO] Worker exiting (pid: 19476)
[2016-07-31 14:15:40 +0000] [19479] [INFO] Worker exiting (pid: 19479)
[2016-07-31 14:15:40 +0000] [19480] [INFO] Worker exiting (pid: 19480)
[2016-07-31 14:15:40 +0000] [19471] [INFO] Shutting down: Master
[2016-07-31 14:15:58 +0000] [19634] [DEBUG] Current configuration:
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7fc1ead2fed8>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7fc1ead2fc08>
  pre_fork: <function pre_fork at 0x7fc1ead2fd70>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7fc1ead2faa0>
  pre_exec: <function pre_exec at 0x7fc1ead38500>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7fc1ead380c8>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7fc1ead38b90>
  config: None
  logconfig: None
  check_config: False
  statsd_prefix: 
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7fc1ead38668>
  post_request: <function post_request at 0x7fc1ead38758>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7fc1ead38230>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7fc1ead388c0>
  chdir: /home/ubuntu/djangoApp
  paste: None
  default_proc_name: core.wsgi:application
  errorlog: /home/ubuntu/djangoApp/gunicorn.log
  loglevel: debug
  capture_output: False
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7fc1ead2f938>
  worker_abort: <function worker_abort at 0x7fc1ead38398>
  bind: ['127.0.0.1:8000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7fc1ead38a28>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2016-07-31 14:15:58 +0000] [19634] [INFO] Starting gunicorn 19.6.0
[2016-07-31 14:15:58 +0000] [19634] [DEBUG] Arbiter booted
[2016-07-31 14:15:58 +0000] [19634] [INFO] Listening at: http://127.0.0.1:8000 (19634)
[2016-07-31 14:15:58 +0000] [19634] [INFO] Using worker: sync
[2016-07-31 14:15:58 +0000] [19639] [INFO] Booting worker with pid: 19639
[2016-07-31 14:15:58 +0000] [19640] [INFO] Booting worker with pid: 19640
[2016-07-31 14:15:58 +0000] [19634] [DEBUG] 3 workers
[2016-07-31 14:15:58 +0000] [19643] [INFO] Booting worker with pid: 19643
[2016-07-31 14:16:01 +0000] [19640] [DEBUG] GET /admin/
